### PR TITLE
Add support for Luxafor Bluetooth

### PR DESCRIPTION
**Pull request by volkangurel**
Add support for Luxafor Bluetooth (https://luxafor.com/product/bluetooth/), using the same pattern used for other Luxafor devices.

### CODE REVIEW

**Comment by JnyJny** [comment]
Wow! Thank you Volkan for such a great pull request. I had never looked at the Luxafor Bluetooth product since I had (wrongly) assumed it talked directly to the host's Bluetooth stack rather than having a USB dongle to handle communication. I have some minor nits about formatting and order of inclusion that I'll be happy to address once the PR is merged. I presume that you have a Luxafor Bluetooth and Busylight with these changes are driving it? I'm curious if the lights on the dongle mirror the lights on the dot? I suspect they do but I'd like to confirm my suspicion.

**Comment by JnyJny** [comment]
Absent any answers to my questions, I'm still inclined to accept this pull request since it is relatively uncomplicated. I don't plan on obtaining a Luxafor Bluetooth device in the near future, so it will be supported but unverified until there are reports "in the wild" of the device working. Thank again for the contribution, it is much appreciated!

**Comment by volkangurel** [comment]
Hi, sorry I must have missed the notification last week, didn't see your comment!

Yes, I have a Luxafor Bluetooth which works perfectly with this code. I don't have a Dot but I assume based on how this code works that it mirrors it exactly.

**Comment by JnyJny** [comment]
Thanks for the update, no worries. I guess at some point I'll have to add the Bluetooth and Dot to the test fleet, just to need to recover from the holidays!

**Comment by JnyJny** [comment]
Also, your PR is included in the latest version published to PyPI. If you could give it a test drive and check back here with a thumbs up that would be great!

**Comment by volkangurel** [comment]
Nice, just tested the released version and works on my Luxafor Bluetooth.

**Pull request merged**
