### PR TITLE
Created a generic adapter for serical CDC devices to connect with devices running custom CircuitPython program

### PR DESCRIPTION
**Pull request by freemansoft**
I can't seem to get busylight to pick up my new device when I run `busylight supported`.  I thought this meant it wasn't picking up my drivers. Then I incremented the version number and the command `busylight --version` does not reflect the incremented numbers.  It looks like it is running the installed busylight and not the one from my git repo.

The instructions say the following. I'm assuming this is the top of the busylight git repo.
> cd path/to/busylight

Any ideas off the top of your head?

```
PS C:\Users\joe\Documents\GitHub\busylight> poetry shell
Spawning shell within C:\Users\joe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\busylight-for-humans-qGfsEWtE-py3.9
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

(busylight-for-humans-py3.9) PS C:\Users\joe\Documents\GitHub\busylight> busylight --version
0.26.0
(busylight-for-humans-py3.9) PS C:\Users\joe\Documents\GitHub\busylight> 
```

Maybe this should have been under issues because it was environment but I did a pull request in case there is a code change that I need to make to pick up the environment or version.

### CODE REVIEW

**Comment by JnyJny** [comment]
So, a couple of comments :)

1. An issue would have been a better place to ask about the `poetry` usage.
2. I've never used the Windows environment to write or develop code.
3. I'll be glad to go over this pull request with you and shape it up for inclusion in the package. 

I guess this identifies a weakness in the development documentation:
1. clone the busylight git repository
2. install the poetry tool
3. change directory into the busylight git repository
4. create a new shell using `poetry shell` which also creates a virtual environment
5. install busylight `poetry install -E webapi` installs it into the virtual environment
6. _Now_ you should be interacting with the code in the git repo and not another busylight installed on your system.

At least that's how it works for me on MacOS and Linux, again I have never used poetry on Windows. My understanding is that it _should_ work the way I'm accustomed to but I'm not going to say for certain :) 

Once you've got your development environment working in a repeatable way, we can go thru your proposed changes and clean them up a little bit; fix some typos, don't incrementing version, and other small stuff.

Thank you for the code contribution, I'm very appreciative of that.

**Comment by JnyJny** [comment]
Is [this](https://www.adafruit.com/product/4870) the device you are adding support for?

**Comment by freemansoft** [comment]
Yup.   I created some CircuitPython firmware for it here https://github.com/freemansoft/Adafruit-Trinkey-CircuitPython/tree/main/Indicator-Light-neopixel. Basically, the firmware should work for any Adrafruit board that has onboard NeoPixels.

**Comment by JnyJny** [comment]
So the Trinkey-Neo plugged in via USB presents as a serial device, to which busylight can send commands?  And the Trinkey-Neo is running CircuitPython that further facilitates access to the lights onboard? There are a lot of moving pieces here.

**Comment by freemansoft** [comment]
The Trinkey is a bare board people use for doing projects.  They have no commands or firmware out of the box.  My firmware runs on the board creating the command interface to the 4 RGB LEDs.  

Then BusyLight would talk to that as if it were any other serial device.

I get it if you'd prefer that BusyLight be for commercial products and am happy to close the pull request if you'd rather it be more turnkey.

**Comment by freemansoft** [comment]
This works after testing on a Mac with one minor PID change.
My problem on the PC is that `poetry install -E webapi` fails so it wouldn't link to the source tree.

**Pull request closed without merging**
